Added repositories and IBaseEntity for task HM-6
NDecheva/HotelManager pull request #15
Opened 2024-11-29 08:18 UTC by ivomihailov06

2024-11-29 09:16 UTC, krisi-23 reviewed
IVO FIXE THE ERRORS

2024-11-29 09:16 UTC, krisi-23 commented on HotelManagerMVC/HotelManager.Data/HotelManagerDbContext.cs
> +        public DbSet<Entities.ClientReservation> ClientReservations { get; set; }
Remove entities

2024-11-29 09:16 UTC, krisi-23 commented on HotelManagerMVC/HotelManager.Data/HotelManagerDbContext.cs
> +            modelBuilder.Entity<Entities.ClientReservation>()
Remove entities

2024-11-29 09:16 UTC, krisi-23 commented on HotelManagerMVC/HotelManager.Data/HotelManagerDbContext.cs
> +            modelBuilder.Entity<Entities.ClientReservation>()
Remove entities

2024-11-29 09:16 UTC, krisi-23 commented on HotelManagerMVC/HotelManager.Data/HotelManagerDbContext.cs
> +            modelBuilder.Entity<Entities.ClientReservation>()
Remove entities

2024-11-29 09:16 UTC, krisi-23 commented on HotelManagerMVC/HotelManager.Data/Repos/BaseRepository .cs
> +	public async Task<TModel> GetByIdAsync(int id)
GetByIdIfExistsAsync

2024-11-29 09:24 UTC, krisi-23 reviewed
DONE GOOD JOB IVO

2024-11-30 12:42 UTC, ectky requested changes

2024-11-30 12:42 UTC, ectky commented on HotelManagerMVC/HotelManager.Data/Migrations/20241126120200_Initial.Designer.cs
> -using ProjectManagement.Data;
това не гърми ли?

2024-11-30 12:42 UTC, ectky commented on HotelManagerMVC/HotelManager.Data/Repos/BaseRepository .cs
> +public abstract class BaseRepository<T, TModel> : IBaseRepository<TModel>,IDisposable
оправи форматирането на този клас

2024-11-30 12:42 UTC, ectky commented on HotelManagerMVC/HotelManager.Tests/UnitTest1.cs
> +    public class Tests
?

2024-11-30 12:42 UTC, ectky commented on HotelManagerMVC/HotelManager.Tests/Repos/BaseRepositoryTests.cs
> +    public abstract class BaseRepositoryTests<TRepository, T, TModel>
колко е code coverage-a на репотата?

2024-12-01 07:45 UTC, Petkov06 commented on HotelManagerMVC/HotelManager.Data/Migrations/20241126120200_Initial.Designer.cs
> -using ProjectManagement.Data;
Е тва пак ли го има

2024-12-01 14:09 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManager.Tests/Repos/BaseRepositoryTests.cs
> +    public abstract class BaseRepositoryTests<TRepository, T, TModel>
Не мога да го видя

2024-12-01 14:09 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManager.Data/Migrations/20241126120200_Initial.Designer.cs
> -using ProjectManagement.Data;
> това не гърми ли?

не

2024-12-02 08:04 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManager.Tests/Repos/BaseRepositoryTests.cs
> +    public abstract class BaseRepositoryTests<TRepository, T, TModel>
![image](https://github.com/user-attachments/assets/9d80da8b-5db3-4900-8bfe-8580ccc238ea)

2024-12-02 08:17 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManager.Tests/Repos/BaseRepositoryTests.cs
> +    public abstract class BaseRepositoryTests<TRepository, T, TModel>
![image](https://github.com/user-attachments/assets/f76e4b8b-1f2a-4e84-824c-c7cacdf29b40)

2024-12-02 08:18 UTC, ectky approved these changes

2024-12-02 08:24 UTC, merged