HM-25-Added-ViewModels-ivomihailov06
NDecheva/HotelManager pull request #20
Opened 2024-12-04 06:44 UTC by ivomihailov06

2024-12-04 07:38 UTC, krisi-23 reviewed
Top 10/10

2024-12-05 11:40 UTC, ectky commented
> Top 10/10

Не е 10/10
Опитай пак

2024-12-05 12:11 UTC, ivomihailov06 commented
Какво им има??@ectky

2024-12-05 18:44 UTC, Petkov06 reviewed
помисли, пропуснал си някои неща от ентититата и не преписвай дусловно от тях.

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ChangePasswordVM.cs
добави    [Required] и за другите св-ва

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientDetailsVM.cs
липсва нещо от ентитито, погледни и помисли как ще го направиш.

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientEditVM.cs
помисли дали трябва да добавиш нещо или да премахнеш.

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientReservationDetailsVM.cs
> +        public virtual Client Client { get; set; }
това е грешно помисли какво трябва да промениш.

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientReservationDetailsVM.cs
> +        public virtual Reservation Reservation { get; set; }
тук грешката е същата.
[required] не е нужно в DetailsVM а само в EditVM

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientReservationEditVM.cs
тук липсва нещо добави и колекция от обекти "<SelectListItem">

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/LoginVM.cs
гуд

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public virtual Room Room { get; set; }
това е грешно

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public virtual User User { get; set; }
това също е грешно

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
погледни ентитито, нещо ти липсва

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public bool HasBreakfast { get; set; }
промени визуализацията му като се отвори страницата трябва да изглежда по-подредено.

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public bool IsAllInclusive { get; set; }
тук също като при закуската

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public DateTime CheckOutDate { get; set; }
тук също оправи визуализацията

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public DateTime CheckInDate { get; set; }
тук също оправи визуализацията

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationEditVM.cs
> +        public bool IsAllInclusive { get; set; }
оправи визуализацията, като отвориш страницата Details не трябва IsALLInclusive да е слято.

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationEditVM.cs
> +        public bool HasBreakfast { get; set; }
направи същото, което трябва да направиш и за IsAllinclusive

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomEditVM.cs
помисли

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserDetailsVM.cs
трябва да пормениш някое свойство, помисли кое е.

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
оправи визуализацията на свойствата при отварянето на страницата

2024-12-05 18:44 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomDetailsVM.cs
имаш грешно ентити и листа не е правилен

2024-12-05 19:34 UTC, Petkov06 reviewed
лет'с го бейби

2024-12-05 19:38 UTC, Petkov06 reviewed
не знам вече

2024-12-05 20:06 UTC, Petkov06 reviewed
Оправи грешките и добави RegisterVM

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationEditVM.cs
добави още един лист

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public virtual UserDetailsVM User { get; set; }
това е грешно.

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public virtual RoomDetailsVM Room { get; set; }
това е грешно.

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientReservationDetailsVM.cs
> +        public virtual ClientDetailsVM Client { get; set; }
премахни virtual

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientReservationDetailsVM.cs
> +        public virtual ReservationDetailsVM Reservation { get; set; }
премахни virtual

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientDetailsVM.cs
нещо липсва

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomDetailsVM.cs
> +        public virtual UserDetailsVM User { get; set; }
премахни virtual

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
липсва нещо!

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomEditVM.cs
> +        [DisplayName("Price Per Night Child")]
for child*

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomEditVM.cs
> +        [DisplayName("Price Per Night Adult")]
price for adult*

2024-12-05 20:06 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomDetailsVM.cs
нещо липсва

2024-12-05 20:15 UTC, Petkov06 reviewed
опрви грешките

2024-12-05 20:15 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientDetailsVM.cs
> +        public virtual List<ClientReservationDetailsVM> ClientReservation { get; set; }
оправи списъка

2024-12-05 20:15 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationEditVM.cs
оправи списъците!

2024-12-05 20:15 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomEditVM.cs
премахни списъка

2024-12-05 20:32 UTC, Petkov06 reviewed
оправи грешките

2024-12-05 20:32 UTC, Petkov06 commented on HotelManagerMVC/HotelManager.Data/Entities/Client.cs
оправи го

2024-12-05 20:32 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientReservationDetailsVM.cs
оправи си го

2024-12-05 20:32 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
добави конструктор

2024-12-05 20:32 UTC, Petkov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationEditVM.cs
оправи си го

2024-12-05 20:35 UTC, Petkov06 reviewed
уел доне

2024-12-05 20:59 UTC, ectky requested changes

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientDetailsVM.cs
> +        public bool? IsAdult { get; set; }
защо е нулабъл?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientEditVM.cs
> +        public bool? IsAdult { get; set; }
защо е нулабъл?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientReservationEditVM.cs
> +        public int ClientId { get; set; }
и от къде ще вземеш тези ид-та?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RegisterVM.cs
> +    public class RegisterVM
могат ли хората сами да се регистрират?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +    public class ReservationDetailsVM : BaseVM
липсва нещо

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationEditVM.cs
> +        public virtual List<UserDetailsVM> Users { get; set; }
?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationEditVM.cs
> +        public virtual List<RoomDetailsVM> Rooms { get; set; }
?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public bool? HasBreakfast { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationDetailsVM.cs
> +        public bool? IsAllInclusive { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationEditVM.cs
> +        public bool? HasBreakfast { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ReservationEditVM.cs
> +        public bool? IsAllInclusive { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomDetailsVM.cs
> +        public bool? IsAvailable { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomDetailsVM.cs
> +        public UserDetailsVM User { get; set; }
?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomDetailsVM.cs
> +    public class RoomDetailsVM : BaseVM
липсва нещо

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomEditVM.cs
> +        public bool? IsAvailable { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomEditVM.cs
> +        public RoomType RoomType { get; set; }
как ще се избере типа?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserDetailsVM.cs
> +        public string Password { get; set; }
паролата пак ли ще я показваме?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserDetailsVM.cs
> +        public DateTime? HireDate { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserDetailsVM.cs
> +        public bool? IsActive { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
> +        public bool? IsActive { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
> +        public Role Role { get; set; }
от къде ще се избере ролята?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
> +        public DateTime? HireDate { get; set; }
защо nullable?

2024-12-05 20:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
> +        public string Password { get; set; }
паролата на потребителите ли ще можем да едитваме?

2024-12-06 08:08 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
> +        public Role Role { get; set; }
Списък ли трябва да сложа

2024-12-06 08:52 UTC, ectky requested changes

2024-12-06 08:52 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomDetailsVM.cs
> +        public UserDetailsVM User { get; set; }
?

2024-12-06 08:52 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomEditVM.cs
> +        public IEnumerable<SelectListItem> Rooms { get; set; }
Какви са тези стаи?

2024-12-06 08:59 UTC, ectky requested changes

2024-12-06 08:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
> +        public DateTime TerminationDate { get; set; }
как е в ентитито?

2024-12-06 08:59 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserDetailsVM.cs
> +        public DateTime TerminationDate { get; set; }
как е в ентитито?

2024-12-06 09:11 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/RoomDetailsVM.cs
> +        public UserDetailsVM User { get; set; }
Така ли трябва да го направя:

        public ReservationDetailsVM Reservation { get; set; }

2024-12-06 09:17 UTC, Petkov06 reviewed
well done

2024-12-06 09:33 UTC, Petkov06 reviewed
well done

2024-12-06 09:34 UTC, Petkov06 reviewed
good

2024-12-06 09:54 UTC, ectky requested changes

2024-12-06 09:54 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientReservationEditVM.cs
> +        [Required]
защо това е задължително?

2024-12-06 09:54 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientReservationEditVM.cs
> +        [Required]
защо това е задължително?

2024-12-06 09:54 UTC, ectky commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
> +        [Required]
?

2024-12-06 10:07 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
> +        [Required]
?

2024-12-06 10:09 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/UserEditVM.cs
> +        [Required]
Какво му има на това?

2024-12-06 10:11 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientDetailsVM.cs
> +        public virtual List<ClientReservationDetailsVM> ClientReservation { get; set; }
Оправен е. Снощи каза че грешката беше че бях написал  ClientReservation

2024-12-06 10:11 UTC, ivomihailov06 commented on HotelManagerMVC/HotelManagerMVC/ViewModels/ClientDetailsVM.cs
> +        public virtual List<ClientReservationDetailsVM> ClientReservation { get; set; }
Оправен е

2024-12-06 12:46 UTC, ectky approved these changes

2024-12-06 13:41 UTC, merged